name: Docker Build & Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout karo
        uses: actions/checkout@v4

      - name: Docker Hub mein Login karo
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Image Build + Push karo
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: alexageek15/routing-app:latest